<template>
  <div class="landing-bg">
    <div class="landing-img">
      <!-- <p @click="navigateTo('people/1/?format=json');">Luke Skywalker</p> -->
      <!-- Image Map Generated by http://www.image-map.net/ -->
      <img src="../../../images/landing.png" usemap="#image-map"> 
      
      <map name="image-map">
          <area @click="navigateTo('people/4');" target="" alt="darth" title="darth" coords="618,127,631,276,662,368,656,502,637,583,628,624,656,624,683,561,757,544,808,619,820,531,895,476,876,383,857,356,886,329,849,203,810,178,774,190,734,300,706,280,728,156,683,163,664,97,639,109" shape="poly">
          <area @click="navigateTo('planets/4')" target="" alt="moon" title="moon" coords="854,190,901,137,1022,109,1130,140,1206,225,1225,299,1203,401,1116,374,1064,357,999,396,963,323,873,360,892,316,873,258" shape="poly">
          <area @click="navigateTo('people/1/?format=json')" target="" alt="luke" title="luke" coords="888,369,935,337,976,362,993,416,983,483,1061,508,1098,718,879,757,830,715,823,657,822,571,827,533,900,483,893,425" shape="poly">
          <area @click="navigateTo('people/5')" target="" alt="leia" title="leia" coords="990,470,1005,405,1046,378,1085,373,1122,387,1156,402,1189,429,1209,470,1202,521,1189,539,1190,563,1173,583,1150,621,1090,643,1082,600,1065,507" shape="poly">
          <area @click="navigateTo('planets/5')" target="" alt="dagobah" title="dagobah" coords="627,295,576,283,508,322,477,376,481,446,508,492,549,519,601,522,644,517,657,487,654,441,654,410,649,363,642,332" shape="poly">
          <area @click="navigateTo('people/2')" target="" alt="c3p0" title="c3p0" coords="617,636,600,676,572,693,554,722,581,736,596,777,598,809,594,856,593,888,637,894,644,771,662,738" shape="poly">
          <area @click="navigateTo('people/3')" target="" alt="r2d2" title="r2d2" coords="642,665,647,641,669,610,688,580,706,565,725,559,766,570,783,592,793,627,817,661,815,702,823,753,771,766,757,782,727,799,727,849,657,860,652,783,674,724" shape="poly">
          <area @click="navigateTo('vehicles/16')" target="" alt="bomber" title="bomber" coords="1208,568,1231,563,1232,587,1254,602,1287,600,1302,590,1339,585,1358,617,1351,641,1317,676,1287,693,1251,658,1207,649,1156,656,1156,629,1185,592" shape="poly">
      </map>
    </div>
    
    <Credits />

  </div>
</template>



<script>
import Credits from "./Credits";

export default {
  name: "Home",
  components: {
    Credits
  },
  methods: { 
    navigateTo: function(path) {
    console.log("path",path)
    this.$router.push({ name: "detail", params: { searchQuery: path } });
    }
  }
};
</script>



<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.landing-img img{
    width: 100%;
    height: 100%;
    margin: 0 auto;
}

/* img.map, map area {
  outline: none;
} */

</style>
